### ISSUE TITLE
关于雷电3

### ISSUE THREAD

**Issue by Kito-ZP** [Hush-vv/ASRock-Z390-Phantom-Gaming-ITXac-OpenCore-Hackintosh#1]
想问下大佬雷电3目前支持哪些功能？可以外接显卡吗？
我试了试外接显卡报错但是核显可以正常工作
传不了图。。我打最后三行的消息吧
ACPI error: IOAPIC: Version 0x20 Vector 64:111
For GPE 0x17, found both _L17 and _E17 methods (20160930/evgpeinit-544)
ACPI : Executed 52 blocks of module-level executable AML code

系统报告里的雷电那一栏有显示显卡盒的相关信息

**Comment by Kito-ZP** [comment]
![IMG_20200508_012215](https://user-images.githubusercontent.com/57110326/81375671-059d1780-90d0-11ea-9b87-89386942f623.jpg)

**Comment by Kito-ZP** [comment]
系统报告的雷电那一栏只看到一次信息。之后就看不到了

**Comment by Hush-vv** [comment]
> 想问下大佬雷电3目前支持哪些功能可以外接显卡吗？
> 我试了试外接显卡报错但是核显可以正常工作
> 传不了图产品..我打最后三行的消息吧
> ACPI错误：IOAPIC：版本为0x20 Vector 64：111 
> 对于GPE 0x17，找到了_L17和_E17方法（20160930 / evgpeinit-544）
> ACPI：执行了52个模块级可执行AML代码块
> 
> 系统报告里的雷电那一栏有显示显卡盒的相关信息

这个主板的雷电3只有10Gbps，不清楚是否支持，雷电3的那个ssdt也是从fangf哪里拿了的。

**Comment by Hush-vv** [comment]
> 执行

这个主板的雷电3只有10Gbps，是否支持外接显卡我也不清楚，雷电3的那个ssdt也是从fangf哪里拿来的，使用了支持热拔插但是会有很多ACPI错误，https://github.com/fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh  https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/page-67

**Comment by Hush-vv** [comment]
> 系统报告的雷电那一栏只看到一次信息。之后就看不到了

雷电3现在已经可以造正常驱动了，按照教程来即可
