### ISSUE TITLE
找不到雷电控制器 是需要插入雷电设备吗

### ISSUE THREAD

**Issue by wuearl** [Hush-vv/ASRock-Z390-Phantom-Gaming-ITXac-OpenCore-Hackintosh#3]
![image](https://user-images.githubusercontent.com/31372199/83314816-d8ff9a00-a24e-11ea-8645-ac120a80bb50.png)

**Comment by Hush-vv** [comment]
把教程里的全部执行一次看看（涮4.40c的bios、安装雷电驱动、更新雷电固件）

**Comment by wuearl** [comment]
刷好 bios 安装了驱动 然后 无法更新固件 就是提示这个

**Comment by Hush-vv** [comment]
> 刷好bios安装了驱动然后无法更新固件就是提示这个

安装驱动时关闭所有杀毒软件试试，驱动没有安装好固件是不能更新的

**Comment by skipjackyu** [comment]
我也遇到一样的问题了，刷BIOS，安装最新驱动，更新固件的时候总是弹出这个提示。雷电接口目前也不是刚需，后面放弃折腾了。
