### ISSUE TITLE
自动断电重启问题

### ISSUE THREAD

**Issue by raymond2010** [Hush-vv/ASRock-Z390-Phantom-Gaming-ITXac-OpenCore-Hackintosh#4]
10.15.5下，遇到自动断电重启的情况（本来应该进入睡眠），日志中看到这个：

Sleep/Wakes since boot at 2020-06-17 17:39:21 +0800 :0   Dark Wake Count in this sleep cycle:0

请问可能是什么引起的？

**Comment by Hush-vv** [comment]
> 10.15.5下，遇到自动断电重启的情况（本来应该进入睡眠），日志中看到这个：
> 
> 自2020-06-17 17:39:21 +0800：0启动以来的睡眠/唤醒次数：此睡眠周期中的黑暗唤醒计数：0
> 
> 请问可能是什么引起的？

如果按照最新的办法驱动了雷电，需要放弃睡眠

**Comment by raymond2010** [comment]
没驱动雷电呀

**Comment by Hush-vv** [comment]
> 雷电
<img width="656" alt="QQ20200618-111123@2x" src="https://user-images.githubusercontent.com/61744850/84973850-a8779580-b154-11ea-8fe5-863988dc63a6.png">

**Comment by Hush-vv** [comment]
那就不知道了

**Comment by Hush-vv** [comment]
> 没驱动雷电呀

现在更新的我这里测试睡眠已经正常（未驱动雷电）
